@Library('shared') _

log.info 'Starting'
log.warning 'Nothing to do!'

pipeline {
    agent any
    stages {
        stage('Start') {
            steps {
                echo 'Starting build step'
            }
        }

        stage('Build') {
            steps {
                bat 'mvn clean install -Dlicense.skip=true'
            }
        }

    }
}